# Generated by Django 6.0.2 on 2026-04-08 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('ciudad', models.CharField(blank=True, default='Bogotá', max_length=80)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('airpods', 'AirPods'), ('iphone', 'iPhone'), ('samsung', 'Samsung'), ('accesorio', 'Accesorio'), ('otro', 'Otro')], default='airpods', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.PositiveIntegerField(help_text='Precio en pesos COP')),
                ('precio_old', models.PositiveIntegerField(blank=True, help_text='Precio tachado', null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('producto_txt', models.CharField(max_length=200, verbose_name='Producto solicitado')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje / dirección')),
                ('estado', models.CharField(choices=[('nuevo', '🆕 Nuevo'), ('contactado', '📞 Contactado'), ('enviado', '🚚 Enviado'), ('entregado', '✅ Entregado'), ('cancelado', '❌ Cancelado')], default='nuevo', max_length=20)),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='landing.cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado'],
            },
        ),
    ]
